### ISSUE TITLE
Different LCD

### ISSUE THREAD

**Issue by TechStuffGuy** [MajicDesigns/FX888-Controller#1]
This is good and simple project. But just for try it out and see the screen is bit tricky...
How to "easily change it to a more common I2C interface" or have here even third version too for parallel LCD in case there is free outputs?
Thanks.

**Comment by MajicDesigns** [comment]
You should be able to change the LCD type by the header files and change the hardware. The rest should just work as function calls except for initialisation are the same.

Marco

**Comment by TechStuffGuy** [comment]
Not so simple (for me :-) ) Got it working! I see the light!
For parallel LCD example:
1 - replace in all files **#include <LiquidCrystal_SR.h>** with your choice **#include <LiquidCrystal.h>**
2 - replace everywhere in all files **LiquidCrystal_SR** with your choice **LiquidCrystal**
3 - in FX888_Controller.ino replace now
**LCD_Display   disp(LCD_DAT_PIN, LCD_CLK_PIN);**
with this
**LCD_Display   disp(LCD_RS, LCD_EN, LCD_D4, LCD_D5, LCD_D6, LCD_D7);**
4 - in Hardware.h replace now:
**// LCD with SR Display
const uint8_t LCD_CLK_PIN = 9;  // SR clock pin
const uint8_t LCD_DAT_PIN = 8;  // SR data pin**
with this
**// 4 bit LCD Display
const uint8_t  LCD_RS = 16;
const uint8_t  LCD_EN = 15;
const uint8_t  LCD_D4 = 14;
const uint8_t  LCD_D5 = 13;
const uint8_t  LCD_D6 = 12;
const uint8_t  LCD_D7 = 11;**
5 - in LCD_Display.h replace now:
**LCD_Display(uint8_t DAT, uint8_t CLK) : LiquidCrystal(DAT, CLK)**
with this
**LCD_Display(uint8_t RS, uint8_t EN, uint8_t D4, uint8_t D5, uint8_t D6, uint8_t D7) : LiquidCrystal(RS, EN, D4, D5, D6, D7)**

Is this good enough?

**Comment by MajicDesigns** [comment]
If it works then it is good enough.

Marco
